tunnel: homelab-new-tunnel
credentials-file: ~/.cloudflared/[tunnel-ID].json

ingress:
  # SSH over WebSocket
  - hostname: ssh.shooonng.com
    service: ssh://192.168.3.13:22

  # Web-based Terminal
  - hostname: terminal.shooonng.com
    service: http://192.168.3.15:7681

  # Monitering
  - hostname: grafana.shooonng.com
    service: http://192.168.3.21:3000

  - hostname: prometheus.shooonng.com
    service: http://192.168.3.21:9090

  # Catch all
  - service: http_status:404
