# Proxmox ホストの構成管理
---
all:
  children:
    pve:
      hosts:
        proxmox-home:
          ansible_host: 192.168.3.100
          ansible_user: root
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519_mgmt"
